version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JWT_SECRET=hararghe_container_secret_2026
      - ENABLE_CBE_BIRR=true
      - ENABLE_TELEBIRR=false
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
